#!/usr/bin/env bash
DIR=/opt/router/blacklist/list
mkdir -p $DIR
cd $DIR
wget -N https://antifilter.download/list/ipsum.lst https://antifilter.download/list/subnet.lst
curl https://core.telegram.org/resources/cidr.txt -o telegram.lst
old=$(cat $DIR/md5.txt);
new=$(cat $DIR/*.lst | md5sum | head -c 32);
if [ "$old" != "$new" ]
then
cat $DIR/*.lst | sort -u | grep -v ":" | sed 's_.*_route & reject;_' > /etc/bird/conf.d/antifilter.conf
/usr/sbin/birdc configure;
logger "RKN list reconfigured";
echo $new > $DIR/md5.txt;
fi
